### PR TITLE
Fix callback function

### PR DESCRIPTION
**Pull request by half2me**

### CODE REVIEW

**Comment by half2me** [comment]
self is already passed automatically

**Comment by SamyCookie** [comment]
Yes... and no.
I added this parameter myself for my use. The 'self' you described 

> self is already passed automatically

 normally corresponds to an 'EventCallback' object. The 'self' variable I pass to the parameter is the 'channel' object corresponding to the message.
It is necessary to me (and maybe useful for others), but you can ignore it by changing the prototype of your EventCallback subclass by
`def process(self, msg, _channel):` or `def process(self, msg, *args):`

I think that the callback part of the code is unclear and should be reworked, but I can't add your fix because it will break my code. Thanks anyway.

**Comment by SamyCookie** [comment]
I have fixed example code at

https://github.com/SamyCookie/python-ant/blob/21be6141b12555121ae534f9839aba5bfc5a9ab4/demos/ant.core/04-processevents.py#L22

**Comment by half2me** [comment]
thanks @SamyCookie :)

**Pull request closed without merging**
