### PR TITLE
Add "six" version constraint (1.10.0+)

### LINKED ISSUE #8: Updated Six Requirement
I'm trying one of the examples and I'm getting this error for my import:
10: `from ant.core import node`
I'm using OSX El Capitan and python 2.7
File "/.../myscript.py", line 10, in <module>
    from ant.core import node
  File "build/bdist.macosx-10.11-intel/egg/ant/core/node.py", line 32, in <module>
  File "build/bdist.macosx-10.11-intel/egg/ant/core/event.py", line 37, in <module>
  File "build/bdist.macosx-10.11-intel/egg/ant/core/message.py", line 71, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py", line 566, in with_metaclass
    return meta("NewBase", bases, {})
  File "build/bdist.macosx-10.11-intel/egg/ant/core/message.py", line 42, in **init**
AttributeError: type object 'NewBase' has no attribute 'type'

### PR DESCRIPTION
**Pull request by half2me**
fixes #8

### CODE REVIEW

**Comment by SamyCookie** [comment]
It seems to work since version 1.7. Please set this version in setup.py.

**Comment by half2me** [comment]
@SamyCookie changed to 1.7 :)

**Comment by SamyCookie** [comment]
Thanks, could you squash the commits please ?

**Comment by half2me** [comment]
@SamyCookie You can squash the commits when merging the PR (New github feature :)

**Comment by SamyCookie** [comment]
Ah ok good then :)

**Pull request merged**
