### PR TITLE
Problem with unexpected keyword argument

### PR DESCRIPTION
**Pull request by David-Hari**
Even with the pylint comment (which I assume is a directive for the linter), I still get an error when running in Python 3:

```
pi@raspberrypi ~/bicycle-monitor $ python3 main.py
Starting ANT node
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/bicycle-monitor/ant/core/event.py", line 60, in EventPump
    msg = Message.decode(buffer_)
  File "/home/pi/bicycle-monitor/ant/core/message.py", line 122, in decode
    msg = Message(type=type_)  # pylint: disable=unexpected-keyword-arg
TypeError: __init__() got an unexpected keyword argument 'type'
```

I have added the **kwargs to get around this, but I am getting other errors now.
Would it be ok if I were to ask you more questions via email? Your email is not visible on GitHub, but mine is. Send me an email if you wish to help.
thanks

### CODE REVIEW

**Comment by SamyCookie** [comment]
Ok, I can reproduce this bug. I do not use Python3 yet, so I have not detected this error before today.
Let me try to find out why this bug happens. I will warn you if I can't find anything about this.

**Comment by SamyCookie** [comment]
Ok this one is fixed. The main issue is the different syntax for metaclasses between python2/3.
Unfortunately, for a simpler and faster fix, I decided to depend on six module.
And unfortunately again, there are another compatibility 2/3 issues after this one, but I let you try to fix them. If you won't succeed, I'll try to fix them for the end of the week.
Please open a new pull request if you succeed.

**Comment by SamyCookie** [comment]
New fixes available.

**Comment by SamyCookie** [comment]
PS: Thanks for reporting this.

**Comment by David-Hari** [comment]
Ok thanks. For the future, could you please enable issue tracking in this project so people can raise issues instead of having to submit pull requests ("request pulls"?) when they may not know how to fix the issue.

**Comment by SamyCookie** [comment]
Oh ! I didn't see that it was disabled by default. I open it then. Thanks !

**Pull request closed without merging**
